### ISSUE TITLE
Error appears when I am trying to train model on my dataset

### ISSUE THREAD

**Issue by RocketFlash** [Ghadjeres/DeepBach#13]
Hello! 
Thank you for interesting project and code! 

I have a problem when I am trying to train model on my dataset. My dataset is monophonic and has only one voice. I selected NUM_VOICES parameter in data_utils equals to 1.
I created "custom_dataset" folder inside "datasets" folder, put my dataset inside and use this command:
 `python3 deepBach.py --dataset /Users/YagfarovRauf/PycharmProjects/DeepBach-master/datasets/custom_dataset/mydataset -t 15 --timesteps 32 -b 64`

Then all my files got FloatingKeyException and following error occurs:

```FloatingKeyException: File /Users/YagfarovRauf/PycharmProjects/DeepBach-master/datasets/custom_dataset/mydataset/mono99.mid skipped
FloatingKeyException: File /Users/YagfarovRauf/PycharmProjects/DeepBach-master/datasets/custom_dataset/mydataset/mono99.mid skipped
FloatingKeyException: File /Users/YagfarovRauf/PycharmProjects/DeepBach-master/datasets/custom_dataset/mydataset/mono99.mid skipped
FloatingKeyException: File /Users/YagfarovRauf/PycharmProjects/DeepBach-master/datasets/custom_dataset/mydataset/mono99.mid skipped
FloatingKeyException: File /Users/YagfarovRauf/PycharmProjects/DeepBach-master/datasets/custom_dataset/mydataset/mono99.mid skipped
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [02:25<00:00,  1.36s/it]
0 files written in datasets/custom_dataset/mydataset.pickle
/usr/local/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((160,), 8) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
Traceback (most recent call last):
  File "deepBach.py", line 847, in <module>
    if __name__ == '__main__':
  File "deepBach.py", line 826, in main
    create_models(model_name, create_new=overwrite, num_units_lstm=num_units_lstm, num_dense=num_dense,
  File "deepBach.py", line 588, in create_models
    labels) = next(gen)
  File "/Users/YagfarovRauf/PycharmProjects/DeepBach-master/data_utils.py", line 365, in generator_from_raw_dataset
    chorale_index = np.random.choice(chorale_indices)
  File "mtrand.pyx", line 1397, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:15477)
ValueError: a must be non-empty

**Comment by RocketFlash** [comment]
I fixed it changing metadatas variable in main() function

**Comment by DenisSKK** [comment]
Probably late on this but, is there a chance you still have your code on how to re-train DeepBach with your own dataset?
Also, was it just any piano midi dataset or was it something specific?

**Comment by RocketFlash** [comment]
@DenisSKK unfortunately no, 7 years have passed:)

**Comment by DenisSKK** [comment]
Bummer. Thanks anyway :))
