### ISSUE TITLE
must create a folder called raw_dataset

### ISSUE THREAD

**Issue by DefinitlyEvil** [Ghadjeres/DeepBach#14]
```
Traceback (most recent call last):
  File "deepBach.py", line 847, in <module>
    main()
  File "deepBach.py", line 775, in main
    voice_ids=[0, 1, 2, 3])
  File "X:\Library\DeepBach\data_utils.py", line 591, in initialization
    metadatas=metadatas)
  File "X:\Develop\Library\DeepBach\data_utils.py", line 247, in make_dataset
    pickle.dump(dataset, open(dataset_name, 'wb'), pickle.HIGHEST_PROTOCOL)
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/raw_dataset/bach_dataset.pickle'
```

**Comment by Ghadjeres** [comment]
Indeed, 
34dd415e37aa3713564bf111da92d05a2813a674 should solve this issue.

**Comment by DefinitlyEvil** [comment]
thanks xD it made so angry cuz I waited 30 mins to create dataset then it failed at the end lol
