### ISSUE TITLE
Problem with Installation High Sierra

### ISSUE THREAD

**Issue by Screpach** [Ghadjeres/DeepBach#38]
I'm completely new in this world, but I'm Musicologist and Historically Informed Performance violin player. And I've decided to try this program with some Renaissance music. I've followed installation requirements but when I typed: 
`python3 deepBach.py -l 100`

this message appeared:
```
Using TensorFlow backend.
Namespace(batch_size_train=128, dataset='', ext='', length=100, midi_file=None, name='deepbach', num_dense=200, num_iterations=20000, num_units_lstm=[200, 200], output_file='', overwrite=False, parallel=1, reharmonization=None, steps_per_epoch=500, timesteps=16, train=0, validation_steps=20)
Creating dataset
Traceback (most recent call last):
  File "deepBach.py", line 183, in <module>
    main()
  File "deepBach.py", line 97, in main
    voice_ids=[0, 1, 2, 3])
  File "/Users/screpach/DeepBach/DeepBach/data_utils.py", line 658, in initialization
    corpus.getBachChorales(fileExtensions='xml'))
AttributeError: module 'music21.corpus' has no attribute 'getBachChorales'
```

How can I make it work, or can you give me more detalles information about installation, please?

## Installed on my comp:
MacOS: 10.13.2
Tensorflow: 1.4.1 _(w/ SSE4.1, SSE4.2, AVX, AVX2, FMA)_ from: [https://github.com/lakshayg/tensorflow-build/blob/master/README.md](url)
Flask: 0.12
Music21: v5.0.5a2
Keras: 2.1.2

**Comment by Ghadjeres** [comment]
Hi,
Thanks for your interest and sorry for the late answer.
The problem comes from the recent update of music21 (v5) which has removed the getBachChorales command, see http://web.mit.edu/music21/doc/moduleReference/moduleCorpusChorales.html.
You can either install the previous version of music21 or directly
replace corpus.getBachChorales by corpus.chorales.ChoraleList().
I'll fix this later.

**Comment by iooops** [comment]
Seems it's not yet fixed..

**Comment by bbbmusic** [comment]
Downloading Music21 v.4 Release (4.1.0) worked on my machine.
High Sierra 10.13.6
