### ISSUE TITLE
follow up on the youtube video last year

### ISSUE THREAD

**Issue by Aerny** [Ghadjeres/DeepBach#61]
Hi Gaëtan, Last year you replied on a comment of me on your YouTube video. 
This is what I wrote: 

Dear Gaëtan, can you make a comprehensive, step by step video on how to install this wonderful invention of yours? I think I almost got it, but for instance - when I paste this code into Terminal: 

shell sudo apt install musescore python -c 'import music21; music21.environment.set("musicxmlPath", "/usr/bin/musescore") 

I get all kinds of error messages: 

apt: invalid flag: install Usage: apt <apt and javac options> <source files> where apt options include: -classpath <path> Specify where to find user class files and annotation processor factories etc. etc. 

I really want to be able to try this out. Already I got it open in Musescore, but I could not do much for it gave this Parse error: 

Debug: on run called Debug: calling endpoint models Debug: SyntaxError: JSON.parse: Parse error 

Probably I need to call some files from somewhere else, but I don't know how to do this. Once explained properly I will never forget it ;-) 

So, can you take the effort? That would be wonderful! Thank you in advanced. Sincerely, Arnold Veeman

**Comment by Aerny** [comment]
I tried to open it with terminal, firing up a python file:
The way I think is wrong I assume, but this is the way I think it may be most intuitive way, but it didn't work out the way I want it. Please help ;-)

mac-pro-van-arnold-veeman:~ arnoldveeman$ cd /Users/arnoldveeman/DeepBach
mac-pro-van-arnold-veeman:DeepBach arnoldveeman$ python3 -u deepBach.py
Traceback (most recent call last):
  File "deepBach.py", line 7, in <module>
    from DatasetManager.chorale_dataset import ChoraleDataset
  File "/Users/arnoldveeman/DeepBach/DatasetManager/chorale_dataset.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
mac-pro-van-arnold-veeman:DeepBach arnoldveeman$ 

Thanks in advanced!

**Comment by Aerny** [comment]
Okay, well... I spent my hours trying to get it up and running for today . . . If you read this can you or anyone else that knows how this works explain it to me? (I know I sound like a savage . . . but it becomes a bit frustrating to try out so many things and not get things done properly. I just don't understand how it works. Starting to, but I am not nearly there)

**Comment by Ghadjeres** [comment]
Hi Arnold,
Have you run the installation commands?
If so, the latest error might come from the fact you need to go into the deepbach_pytorch environment.
(This is done automatically the first time you create the environment but you have to run
`conda activate deepbach_pytorch` each time you open a new terminal)
Then the "No module named 'torch'" should disappear.

But for musescore, you need to launch the  
`python musescore_flask_server.py` command.
Normally, you should be able to select a region in musescore and click on compose in the plugin.

Depending on your needs, maybe you would like to check the Usage with NONOTO (https://github.com/SonyCSLParis/NONOTO) part.

Keep me updated!
Bets

**Comment by Aerny** [comment]
Hi Gaëtan, thanks for your reply!
I can't find deepbach_pytorch in any directory so I can't fire it up.
Will try the entire sequence once again.

**Comment by Aerny** [comment]
Last login: Tue Jul  9 18:15:46 on ttys000
mac-pro-van-arnold-veeman:~ arnoldveeman$ git clone git@github.com:SonyCSL-Paris/DeepBach.git
fatal: destination path 'DeepBach' already exists and is not an empty directory.
mac-pro-van-arnold-veeman:~ arnoldveeman$ cd DeepBach
mac-pro-van-arnold-veeman:DeepBach arnoldveeman$ conda env create --name deepbach_pytorch -f environment.yml
Solving environment: failed

ResolvePackageNotFound: 
  - xz==5.2.4=h14c3975_4
  - libgcc-ng==8.2.0=hdf63c60_1
  - libtiff==4.0.9=he85c1e1_2
  - ncurses==6.1=he6710b0_1
  - libpng==1.6.35=hbc83047_0
  - cffi==1.11.5=py36he75722e_1
  - tk==8.6.8=hbc83047_0
  - libstdcxx-ng==8.2.0=hdf63c60_1
  - ninja==1.8.2=py36h6bb024c_1
  - libedit==3.1.20170329=h6b74fdf_2
  - jpeg==9b=h024ee3a_2
  - libffi==3.2.1=hd88cf55_4
  - freetype==2.9.1=h8a8886c_1
  - readline==7.0=h7b6447c_5
  - numpy==1.15.4=py36h7e9f1db_0
  - numpy-base==1.15.4=py36hde5b4d6_0
  - mkl_fft==1.0.6=py36hd81dba3_0
  - sqlite==3.26.0=h7b6447c_0
  - python==3.6.8=h0371630_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - mkl_random==1.0.2=py36hd81dba3_0
  - pillow==5.3.0=py36h34e0f95_0
  - openssl==1.1.1a=h7b6447c_0
  - pytorch==1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
  - zlib==1.2.11=h7b6447c_3

mac-pro-van-arnold-veeman:DeepBach arnoldveeman$ bash dl_dataset_and_models.sh
dl_dataset_and_models.sh: line 2: wget: command not found
tar: Error opening archive: Failed to open 'deepbach_pytorch_resources.tar.gz'
mv: rename resources/dataset_cache to DatasetManager/dataset_cache: No such file or directory
mv: rename resources/models to ./models: No such file or directory
rm: resources: No such file or directory
mac-pro-van-arnold-veeman:DeepBach arnoldveeman$

**Comment by Aerny** [comment]
I really don't understand it... 

I tried to fire it up by using the 4 commands: 
1 - git clone git@github.com:SonyCSL-Paris/DeepBach.git (probably to get the files from a server in Paris)
2 - cd DeepBach (to get into the Deepbach directory)
3 - conda env create --name deepbach_pytorch -f environment.yml (to create some sort of an environment to get the entire thing started)
4 - bash dl_dataset_and_models.sh (and to download the models that would drive the database)

What I would really like to see is a step by step method start your software up? I hope you understand what I mean?

p.s. and also; when I try to create the python file musescore_flask_server.py it says that there is no module named 'tqdm'. I don't know what that means, but it seems to me that there is no reference to that 'tqdm' file in the musescore_flask_server.py file?

**Comment by Aerny** [comment]
Traceback (most recent call last):
  File "musescore_flask_server.py", line 12, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
mac-pro-van-arnold-veeman:DeepBach arnoldveeman$
