### ISSUE TITLE
Error when running server

### ISSUE THREAD

**Issue by xmasterlnm** [Ghadjeres/DeepBach#71]
Hello. I have been trying to run the server, but I think I have missed something. I will list the traceback below:

D:\DeepBach>python musescore_flask_server.py
Creating ChoraleDataset([0, 1, 2, 3],bach_chorales,['fermata', 'tick', 'key'],8,4), both tensor dataset and parameters
Creating ChoraleDataset([0, 1, 2, 3],bach_chorales,['fermata', 'tick', 'key'],8,4) TensorDataset since it is not cached
Making tensor dataset
Computing index dicts
351it [00:11, 30.46it/s]
Computing voice ranges
4it [00:00, 1976.11it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "musescore_flask_server.py", line 298, in <module>
    init_app()
  File "C:\Users\lucas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lucas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\lucas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lucas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "musescore_flask_server.py", line 102, in init_app
    bach_chorales_dataset: ChoraleDataset = dataset_manager.get_dataset(
  File "D:\DeepBach\DatasetManager\dataset_manager.py", line 42, in get_dataset
    return self.load_if_exists_or_initialize_and_save(
  File "D:\DeepBach\DatasetManager\dataset_manager.py", line 85, in load_if_exists_or_initialize_and_save
    tensor_dataset = dataset.tensor_dataset
  File "D:\DeepBach\DatasetManager\music_dataset.py", line 133, in tensor_dataset
    self._tensor_dataset = self.make_tensor_dataset()
  File "D:\DeepBach\DatasetManager\chorale_dataset.py", line 106, in make_tensor_dataset
    metadata_tensor) = self.transposed_score_and_metadata_tensors(
  File "D:\DeepBach\DatasetManager\chorale_dataset.py", line 158, in transposed_score_and_metadata_tensors
    str(interval_nature) + interval_type)
TypeError: can only concatenate str (not "Specifier") to str

**Comment by Ghadjeres** [comment]
Hi,
It might be that this is caused because your are using a different version of music21.
I used music21==5.5.0, and they probably changed some things since then (the latest version is >= 6.3).
Also I only tested the musescore plugin with MuseScore2 and I remember having some issues with Musescore3.
Hope it'll work.
